### Teste da API
GET http://localhost:3333/

### Criar novo usuario
POST http://localhost:3333/usuarios
Content-Type: application/json

{
  "nome": "Higor",
  "email": "higor@mail.com",
  "idade": 28
}

### Listar usuario
GET http://localhost:3333/usuarios

